import { SectorInfo } from '../types/sectors';

export const INITIAL_ANTOFAGASTA_SECTORS: SectorInfo[] = [
  // =========================================================================
  // SECTOR NORTE
  // =========================================================================
  {
    id: 'costa_laguna',
    name: 'Costa Laguna (Norte)',
    macroZone: 'SECTOR_NORTE',
    unidadOficial: 'La Portada',
    subsector: 'Costa Laguna',
    tipoTerritorio: 'Residencial costero',
    callesHitos: 'La Portada, franja costera norte, acceso norte litoral',
    prioridadAlerta: 'Media',
    estadoFuente: 'Operativo',
    category: 'COSTA_URBANO',
    lat: -23.541,
    lng: -70.384,
    altitudeMeters: 25,
    description: 'Sector residencial costero norte de Antofagasta. Zona urbana plana expuesta a viento marino.',
    isKeyFocusArea: true,
    currentRisk: 'VERDE',
    snowRisk: false,
    eventRisk: false,
    riskReason: 'Condiciones normales en tiempo real. Sin nieve (25m msnm).',
    tempCelsius: 16.5,
    windSpeedKmH: 18,
    precipMmH: 0,
    isotermaZeroMeters: 2800,
  },
  {
    id: 'la_portada_litoral',
    name: 'La Portada Litoral (Norte)',
    macroZone: 'SECTOR_NORTE',
    unidadOficial: 'La Portada',
    subsector: 'La Portada litoral',
    tipoTerritorio: 'Costero / turístico',
    callesHitos: 'Monumento Natural La Portada, borde costero norte',
    prioridadAlerta: 'Alta',
    estadoFuente: 'Mixto',
    category: 'COSTA_URBANO',
    lat: -23.504,
    lng: -70.422,
    altitudeMeters: 40,
    description: 'Monumento natural y acantilados costeros del sector norte.',
    isKeyFocusArea: false,
    currentRisk: 'VERDE',
    snowRisk: false,
    eventRisk: false,
    riskReason: 'Viento costero y fuerte marejada matinal.',
    tempCelsius: 16.0,
    windSpeedKmH: 22,
    precipMmH: 0,
    isotermaZeroMeters: 2800,
  },
  {
    id: 'acceso_juan_lopez',
    name: 'Acceso Juan López / B-446 (Norte)',
    macroZone: 'SECTOR_NORTE',
    unidadOficial: 'La Portada',
    subsector: 'Acceso Juan López / B-446',
    tipoTerritorio: 'Ruta / borde urbano norte',
    callesHitos: 'Ruta B-446, bajada a Juan López',
    prioridadAlerta: 'Alta',
    estadoFuente: 'Oficial',
    category: 'COSTA_URBANO',
    lat: -23.490,
    lng: -70.435,
    altitudeMeters: 55,
    description: 'Corredor vial costero y acceso a balneario Juan López.',
    isKeyFocusArea: false,
    currentRisk: 'VERDE',
    snowRisk: false,
    eventRisk: false,
    riskReason: 'Tránsito normal en ruta B-446.',
    tempCelsius: 16.2,
    windSpeedKmH: 24,
    precipMmH: 0,
    isotermaZeroMeters: 2800,
  },
  {
    id: 'la_chimba',
    name: 'La Chimba (Norte)',
    macroZone: 'SECTOR_NORTE',
    unidadOficial: 'La Chimba',
    subsector: 'La Chimba',
    tipoTerritorio: 'Residencial expansión',
    callesHitos: 'Sector urbano norte inmediato a la ciudad consolidada',
    prioridadAlerta: 'Media',
    estadoFuente: 'Oficial',
    category: 'COSTA_URBANO',
    lat: -23.570,
    lng: -70.390,
    altitudeMeters: 35,
    description: 'Barrio residencial en expansión del sector norte.',
    isKeyFocusArea: false,
    currentRisk: 'VERDE',
    snowRisk: false,
    eventRisk: false,
    riskReason: 'Cielos nublados matinales.',
    tempCelsius: 16.8,
    windSpeedKmH: 19,
    precipMmH: 0,
    isotermaZeroMeters: 2800,
  },
  {
    id: 'la_chimba_alto',
    name: 'La Chimba Alto (Norte)',
    macroZone: 'SECTOR_NORTE',
    unidadOficial: 'La Chimba',
    subsector: 'La Chimba Alto',
    tipoTerritorio: 'Ladera / borde cerro',
    callesHitos: 'Sector alto de La Chimba, ladera cerro',
    prioridadAlerta: 'Alta',
    estadoFuente: 'Mixto',
    category: 'COSTA_URBANO',
    lat: -23.565,
    lng: -70.375,
    altitudeMeters: 120,
    description: 'Sector de ladera urbana sensible a escorrentías.',
    isKeyFocusArea: false,
    currentRisk: 'VERDE',
    snowRisk: false,
    eventRisk: false,
    riskReason: 'Viento constante de ladera.',
    tempCelsius: 15.8,
    windSpeedKmH: 26,
    precipMmH: 0,
    isotermaZeroMeters: 2800,
  },
  {
    id: 'bonilla',
    name: 'Bonilla (Norte)',
    macroZone: 'SECTOR_NORTE',
    unidadOficial: 'Norte Tirado',
    subsector: 'Bonilla',
    tipoTerritorio: 'Residencial denso / borde cerro',
    callesHitos: 'Bonilla; alta concentración poblacional en borde cerro',
    prioridadAlerta: 'Alta',
    estadoFuente: 'Mixto',
    category: 'COSTA_URBANO',
    lat: -23.590,
    lng: -70.380,
    altitudeMeters: 80,
    description: 'Sector residencial denso en borde cerro del norte.',
    isKeyFocusArea: false,
    currentRisk: 'VERDE',
    snowRisk: false,
    eventRisk: false,
    riskReason: 'Condiciones estables de temperatura.',
    tempCelsius: 16.4,
    windSpeedKmH: 20,
    precipMmH: 0,
    isotermaZeroMeters: 2800,
  },
  {
    id: 'los_arenales',
    name: 'Los Arenales (Norte)',
    macroZone: 'SECTOR_NORTE',
    unidadOficial: 'Norte Tirado',
    subsector: 'Los Arenales',
    tipoTerritorio: 'Residencial / interior',
    callesHitos: 'Borde cerro centro-norte, sector referencial',
    prioridadAlerta: 'Media',
    estadoFuente: 'Operativo',
    category: 'COSTA_URBANO',
    lat: -23.600,
    lng: -70.385,
    altitudeMeters: 75,
    description: 'Sector poblacional de transición centro-norte.',
    isKeyFocusArea: false,
    currentRisk: 'VERDE',
    snowRisk: false,
    eventRisk: false,
    riskReason: 'Cielo nublado matinal.',
    tempCelsius: 16.5,
    windSpeedKmH: 18,
    precipMmH: 0,
    isotermaZeroMeters: 2800,
  },

  // =========================================================================
  // SECTOR CENTRO
  // =========================================================================
  {
    id: 'centro_historico',
    name: 'Centro Histórico (Centro)',
    macroZone: 'SECTOR_CENTRO',
    unidadOficial: 'Centro',
    subsector: 'Centro Histórico',
    tipoTerritorio: 'Centro cívico / comercial',
    callesHitos: 'Plaza Colón y damero fundacional',
    prioridadAlerta: 'Media',
    estadoFuente: 'Oficial',
    category: 'COSTA_URBANO',
    lat: -23.650,
    lng: -70.400,
    altitudeMeters: 15,
    description: 'Radio urbano cívico, bancario y comercial de Antofagasta.',
    isKeyFocusArea: false,
    currentRisk: 'VERDE',
    snowRisk: false,
    eventRisk: false,
    riskReason: 'Operación normal de la ciudad.',
    tempCelsius: 17.2,
    windSpeedKmH: 14,
    precipMmH: 0,
    isotermaZeroMeters: 2800,
  },
  {
    id: 'barrio_estacion',
    name: 'Barrio Estación (Centro)',
    macroZone: 'SECTOR_CENTRO',
    unidadOficial: 'Centro',
    subsector: 'Barrio Estación',
    tipoTerritorio: 'Central / transición',
    callesHitos: 'Entorno Estación y ejes ferroviarios FCAB',
    prioridadAlerta: 'Media',
    estadoFuente: 'Mixto',
    category: 'COSTA_URBANO',
    lat: -23.642,
    lng: -70.395,
    altitudeMeters: 25,
    description: 'Eje histórico ferroviario y patrimonial céntrico.',
    isKeyFocusArea: false,
    currentRisk: 'VERDE',
    snowRisk: false,
    eventRisk: false,
    riskReason: 'Tránsito normal en eje FCAB.',
    tempCelsius: 17.0,
    windSpeedKmH: 15,
    precipMmH: 0,
    isotermaZeroMeters: 2800,
  },
  {
    id: 'bellavista',
    name: 'Bellavista (Centro)',
    macroZone: 'SECTOR_CENTRO',
    unidadOficial: 'Centro',
    subsector: 'Bellavista',
    tipoTerritorio: 'Costero urbano',
    callesHitos: 'Borde costero céntrico y puerto',
    prioridadAlerta: 'Media',
    estadoFuente: 'Operativo',
    category: 'COSTA_URBANO',
    lat: -23.635,
    lng: -70.398,
    altitudeMeters: 10,
    description: 'Borde costero y radio puerto del centro.',
    isKeyFocusArea: false,
    currentRisk: 'VERDE',
    snowRisk: false,
    eventRisk: false,
    riskReason: 'Brisa marina suave.',
    tempCelsius: 17.1,
    windSpeedKmH: 18,
    precipMmH: 0,
    isotermaZeroMeters: 2800,
  },
  {
    id: 'parque_brasil',
    name: 'Parque Brasil (Centro)',
    macroZone: 'SECTOR_CENTRO',
    unidadOficial: 'Centro',
    subsector: 'Parque Brasil',
    tipoTerritorio: 'Mixto urbano',
    callesHitos: 'Eje Parque Brasil, Av. O’Higgins',
    prioridadAlerta: 'Media',
    estadoFuente: 'Mixto',
    category: 'COSTA_URBANO',
    lat: -23.658,
    lng: -70.403,
    altitudeMeters: 20,
    description: 'Arterial verde residencial y gastronómica del centro-sur.',
    isKeyFocusArea: false,
    currentRisk: 'VERDE',
    snowRisk: false,
    eventRisk: false,
    riskReason: 'Cielos con nubosidad parcial.',
    tempCelsius: 17.3,
    windSpeedKmH: 14,
    precipMmH: 0,
    isotermaZeroMeters: 2800,
  },
  {
    id: 'gran_via',
    name: 'Gran Vía (Centro Alto)',
    macroZone: 'SECTOR_CENTRO',
    unidadOficial: 'Gran Vía',
    subsector: 'Gran Vía',
    tipoTerritorio: 'Ladera urbana / residencial',
    callesHitos: 'Eje Gran Vía, conexión con Av. Argentina',
    prioridadAlerta: 'Alta',
    estadoFuente: 'Oficial',
    category: 'COSTA_URBANO',
    lat: -23.670,
    lng: -70.408,
    altitudeMeters: 65,
    description: 'Sector residencial denso en ladera urbana centro-sur.',
    isKeyFocusArea: false,
    currentRisk: 'VERDE',
    snowRisk: false,
    eventRisk: false,
    riskReason: 'Temperaturas agradables.',
    tempCelsius: 16.9,
    windSpeedKmH: 19,
    precipMmH: 0,
    isotermaZeroMeters: 2800,
  },
  {
    id: 'salar_del_carmen',
    name: 'Salar del Carmen (Oriente)',
    macroZone: 'SECTOR_CENTRO',
    unidadOficial: 'Salar del Carmen',
    subsector: 'Salar del Carmen',
    tipoTerritorio: 'Interior / quebradas',
    callesHitos: 'Quebrada y corredor Salar del Carmen',
    prioridadAlerta: 'Alta',
    estadoFuente: 'Oficial',
    category: 'COSTA_URBANO',
    lat: -23.645,
    lng: -70.355,
    altitudeMeters: 220,
    description: 'Quebrada crítica al oriente de la ciudad.',
    isKeyFocusArea: false,
    currentRisk: 'VERDE',
    snowRisk: false,
    eventRisk: false,
    riskReason: 'Monitoreo de cauce seco sin novedad.',
    tempCelsius: 15.5,
    windSpeedKmH: 25,
    precipMmH: 0,
    isotermaZeroMeters: 2800,
  },

  // =========================================================================
  // SECTOR SUR
  // =========================================================================
  {
    id: 'coloso',
    name: 'Coloso (Sur)',
    macroZone: 'SECTOR_SUR',
    unidadOficial: 'Coloso',
    subsector: 'Coloso',
    tipoTerritorio: 'Costero sur / residencial',
    callesHitos: 'Puerto Coloso, borde costero sur',
    prioridadAlerta: 'Media',
    estadoFuente: 'Oficial',
    category: 'COSTA_URBANO',
    lat: -23.755,
    lng: -70.465,
    altitudeMeters: 10,
    description: 'Caleta de pescadores y puerto industrial en el extremo sur.',
    isKeyFocusArea: false,
    currentRisk: 'VERDE',
    snowRisk: false,
    eventRisk: false,
    riskReason: 'Viento constante de suroeste.',
    tempCelsius: 16.2,
    windSpeedKmH: 22,
    precipMmH: 0,
    isotermaZeroMeters: 2800,
  },
  {
    id: 'coviefi',
    name: 'Coviefi (Sur)',
    macroZone: 'SECTOR_SUR',
    unidadOficial: 'Coloso',
    subsector: 'Coviefi',
    tipoTerritorio: 'Residencial sur',
    callesHitos: 'Sector sur urbano consolidado, ladera sur',
    prioridadAlerta: 'Media',
    estadoFuente: 'Operativo',
    category: 'COSTA_URBANO',
    lat: -23.682,
    lng: -70.412,
    altitudeMeters: 85,
    description: 'Barrio residencial consolidado del sector sur.',
    isKeyFocusArea: false,
    currentRisk: 'VERDE',
    snowRisk: false,
    eventRisk: false,
    riskReason: 'Condiciones de estabilidad climática.',
    tempCelsius: 16.5,
    windSpeedKmH: 18,
    precipMmH: 0,
    isotermaZeroMeters: 2800,
  },
  {
    id: 'jardines_del_sur',
    name: 'Jardines del Sur (Sur)',
    macroZone: 'SECTOR_SUR',
    unidadOficial: 'Coloso',
    subsector: 'Jardines del Sur',
    tipoTerritorio: 'Residencial costero sur',
    callesHitos: 'Jardines del Sur, Av. Jaime Guzmán',
    prioridadAlerta: 'Media',
    estadoFuente: 'Operativo',
    category: 'COSTA_URBANO',
    lat: -23.700,
    lng: -70.425,
    altitudeMeters: 25,
    description: 'Zona residencial costera del sector sur de la ciudad.',
    isKeyFocusArea: false,
    currentRisk: 'VERDE',
    snowRisk: false,
    eventRisk: false,
    riskReason: 'Brisa costera del pacífico.',
    tempCelsius: 16.8,
    windSpeedKmH: 20,
    precipMmH: 0,
    isotermaZeroMeters: 2800,
  },
  {
    id: 'angamos_sur',
    name: 'Angamos Sur / UCN (Sur)',
    macroZone: 'SECTOR_SUR',
    unidadOficial: 'Coloso',
    subsector: 'Angamos sur',
    tipoTerritorio: 'Corredor urbano / equipamiento',
    callesHitos: 'Av. Angamos, Universidad Católica del Norte',
    prioridadAlerta: 'Media',
    estadoFuente: 'Mixto',
    category: 'COSTA_URBANO',
    lat: -23.678,
    lng: -70.415,
    altitudeMeters: 30,
    description: 'Campus universitario UCN y eje vial sur.',
    isKeyFocusArea: false,
    currentRisk: 'VERDE',
    snowRisk: false,
    eventRisk: false,
    riskReason: 'Flujo vehicular normal.',
    tempCelsius: 17.0,
    windSpeedKmH: 16,
    precipMmH: 0,
    isotermaZeroMeters: 2800,
  },
  {
    id: 'huascar',
    name: 'El Huáscar (Sur)',
    macroZone: 'SECTOR_SUR',
    unidadOficial: 'Coloso',
    subsector: 'Universidad / Huáscar',
    tipoTerritorio: 'Costero / equipamiento',
    callesHitos: 'El Huáscar y borde costero sur',
    prioridadAlerta: 'Media',
    estadoFuente: 'Mixto',
    category: 'COSTA_URBANO',
    lat: -23.720,
    lng: -70.435,
    altitudeMeters: 15,
    description: 'Sector residencial y balneario sur.',
    isKeyFocusArea: false,
    currentRisk: 'VERDE',
    snowRisk: false,
    eventRisk: false,
    riskReason: 'Cielo parcial en litoral sur.',
    tempCelsius: 16.4,
    windSpeedKmH: 22,
    precipMmH: 0,
    isotermaZeroMeters: 2800,
  },

  // =========================================================================
  // CORDILLERA & PUNTOS REGIONALES DE ALTA ALTITUD
  // =========================================================================
  {
    id: 'cerro_paranal',
    name: 'Cerro Paranal (VLT - Cordillera)',
    macroZone: 'CORDILLERA_REGIONAL',
    unidadOficial: 'Cordillera de la Costa',
    subsector: 'Observatorio Paranal',
    tipoTerritorio: 'Cumbre Cordillera de la Costa',
    callesHitos: 'Observatorio ESO, cumbre 2.635 m.s.n.m.',
    prioridadAlerta: 'Alta',
    estadoFuente: 'Oficial',
    category: 'CORDILLERA_COSTA',
    lat: -24.627,
    lng: -70.404,
    altitudeMeters: 2635,
    description: 'Observatorio astronómico en cumbre alta de la Cordillera de la Costa.',
    isKeyFocusArea: false,
    currentRisk: 'NARANJO',
    snowRisk: true,
    eventRisk: true,
    riskReason: 'Isoterma cero a 2.400m msnm. Viento racheado 58 km/h en cumbre.',
    tempCelsius: -1.5,
    windSpeedKmH: 58,
    precipMmH: 2.5,
    isotermaZeroMeters: 2400,
  },
  {
    id: 'cerro_armazones',
    name: 'Cerro Armazones (ELT - Cordillera)',
    macroZone: 'CORDILLERA_REGIONAL',
    unidadOficial: 'Cordillera de la Costa',
    subsector: 'Cumbre Armazones',
    tipoTerritorio: 'Alta Montaña Costera',
    callesHitos: 'Sitio construcción ELT, cumbre 3.046 m.s.n.m.',
    prioridadAlerta: 'Alta',
    estadoFuente: 'Oficial',
    category: 'CORDILLERA_COSTA',
    lat: -24.598,
    lng: -70.192,
    altitudeMeters: 3046,
    description: 'Punto más elevado de la Cordillera de la Costa en la región.',
    isKeyFocusArea: false,
    currentRisk: 'ROJO',
    snowRisk: true,
    eventRisk: true,
    riskReason: 'Riesgo alto de congelamiento en cumbre sobre 3.000m msnm.',
    tempCelsius: -4.2,
    windSpeedKmH: 72,
    precipMmH: 6.0,
    isotermaZeroMeters: 2400,
  },
  {
    id: 'sierra_vicuna_mackenna',
    name: 'Sierra Vicuña Mackenna',
    macroZone: 'CORDILLERA_REGIONAL',
    unidadOficial: 'Cordillera de la Costa',
    subsector: 'Vicuña Mackenna',
    tipoTerritorio: 'Cordillera Alta',
    callesHitos: 'Cadena montañosa costera más alta de Chile (>3.000m)',
    prioridadAlerta: 'Alta',
    estadoFuente: 'Oficial',
    category: 'CORDILLERA_COSTA',
    lat: -24.800,
    lng: -70.250,
    altitudeMeters: 3100,
    description: 'Cadena montañosa costera alta.',
    isKeyFocusArea: false,
    currentRisk: 'ROJO',
    snowRisk: true,
    eventRisk: true,
    riskReason: 'Cota de nieve activa en altitud.',
    tempCelsius: -5.0,
    windSpeedKmH: 80,
    precipMmH: 8.0,
    isotermaZeroMeters: 2400,
  },
  {
    id: 'paso_sico',
    name: 'Paso Sico (Frontera Arg)',
    macroZone: 'CORDILLERA_REGIONAL',
    unidadOficial: 'Alto Andino',
    subsector: 'Paso Sico',
    tipoTerritorio: 'Paso Fronterizo Internacional',
    callesHitos: 'Ruta 23-CH, frontera internacional a 4.080 m.s.n.m.',
    prioridadAlerta: 'Alta',
    estadoFuente: 'Oficial',
    category: 'INTERMEDIA_ANDINA',
    lat: -23.929,
    lng: -67.260,
    altitudeMeters: 4080,
    description: 'Paso fronterizo andino de alta montaña.',
    isKeyFocusArea: false,
    currentRisk: 'ROJO',
    snowRisk: true,
    eventRisk: true,
    riskReason: 'Nevada y viento blanco en alta cordillera andina.',
    tempCelsius: -8.5,
    windSpeedKmH: 85,
    precipMmH: 12.0,
    isotermaZeroMeters: 2200,
  }
];
